[development]
database = "../data/data.db"
id_column = "client_id"
target_column = "target"
train_source = "train"
test_source = "test"
fill_na = -1
silent = false

 	[development.feature_selection]
 	missing_threshold = 0.9
 	disbalance_threshold = 0.9
 	collinear_threshold = 0.9
 	permutation = true
 	permutation_threshold = 0.0005
 	top_features = "../model/top_features.json"
 
 	[development.model_building]
 	model = "../model/model.sav"
 	cat_dict = "../model/cat_dict.npy"
	random_state = 5
 	holdout_size = 0.2
 	cv_splits = 4
 	init_points = 5
 	n_iter = 100
 	cm_threshold = 0.45
 	params_ranges = { "num_leaves" = [ 10, 20 ], "num_iterations" = [ 80, 600 ], "min_data_in_leaf" = [ 100, 400 ], "max_depth" = [ 8, 15 ], "bagging_fraction" = [ 0.6, 0.9 ], "feature_fraction" = [ 0.6, 1.0 ], "max_bin" = [ 500, 1200 ], "colsample_bytree" = [ 0.7, 0.9 ], "learning_rate" = [ 0.01, 0.5 ], "subsample" = [ 0.6, 0.9 ], "min_gain_to_split" = [ 0.01, 0.03 ] }
 	
 	[development.scoring]
 	probability_column = "pred"
 	scoring_table = "scoring_20200323"
 	scoring_filename = "../scoring/scoring_20200323.csv"
	
